- country: Philippines
  isocode: PH
  download:
    - dataset: 'cod-ab-phl'
      resource: 'phl_adminboundaries_candidate_adm3.zip'
    - dataset: 'cod-ab-phl'
      resource: 'phl_adminboundaries_candidate_exclude_adm3.zip'
  processing:
    - source: 'phl_adminboundaries_candidate_exclude_adm3.zip!phl_admbnda_adm0_psa_namria_20200529.shp'
      output: 'admin0'
    - source: 'phl_adminboundaries_candidate_exclude_adm3.zip!phl_admbnda_adm1_psa_namria_20200529.shp'
      output: 'admin1'
    - source: 'phl_adminboundaries_candidate_exclude_adm3.zip!phl_admbnda_adm2_psa_namria_20200529.shp'
      output: 'admin2'
    - source: 'phl_adminboundaries_candidate_adm3.zip'
      output: 'admin3'
- country: Thailand
  isocode: TH
  download:
    - dataset: 'cod-ab-tha'
      resource: 'tha_adm_rtsd_itos_20210121_SHP.zip'
  processing:
    - source: 'tha_adm_rtsd_itos_20210121_SHP.zip!tha_admbnda_adm0_rtsd_20220121.shp'
      output: 'admin0'
    - source: 'tha_adm_rtsd_itos_20210121_SHP.zip!tha_admbnda_adm1_rtsd_20220121.shp'
      output: 'admin1'
    - source: 'tha_adm_rtsd_itos_20210121_SHP.zip!tha_admbnda_adm2_rtsd_20220121.shp'
      output: 'admin2'
    - source: 'tha_adm_rtsd_itos_20210121_SHP.zip!tha_admbnda_adm3_rtsd_20220121.shp'
      output: 'admin3'
- country: Indonesia
  isocode: ID
  download:
    - dataset: 'cod-ab-idn'
      resource: 'idn_adm_bps_20200401_SHP.zip'
  processing:
    - source: 'idn_adm_bps_20200401_SHP.zip!idn_admbnda_adm0_bps_20200401.shp'
      output: 'admin0'
    - source: 'idn_adm_bps_20200401_SHP.zip!idn_admbnda_adm1_bps_20200401.shp'
      output: 'admin1'
    - source: 'idn_adm_bps_20200401_SHP.zip!idn_admbnda_adm2_bps_20200401.shp'
      output: 'admin2'
    - source: 'idn_adm_bps_20200401_SHP.zip!idn_admbnda_adm3_bps_20200401.shp'
      output: 'admin3'
- country: Malaysia
  isocode: MY
  download:
    - dataset: 'cod-ab-mys'
      resource: 'mys_admb_unhcr_20210211_SHP.zip'
  processing:
    - source: 'mys_admb_unhcr_20210211_SHP.zip!mys_admbnda_adm0_unhcr_20210211.shp'
      output: 'admin0'
    - source: 'mys_admb_unhcr_20210211_SHP.zip!mys_admbnda_adm1_unhcr_20210211.shp'
      output: 'admin1'
    - source: 'mys_admb_unhcr_20210211_SHP.zip!mys_admbnda_adm2_unhcr_20210211.shp'
      output: 'admin2'
- country: Vietnam
  isocode: VN
  download:
    - dataset: 'cod-ab-vnm'
      resource: 'vnm_adm_gov_20201027.zip'
  processing:
    - source: 'vnm_adm_gov_20201027.zip!vnm_admbnda_adm0_gov_20200103.shp'
      output: 'admin0'
    - source: 'vnm_adm_gov_20201027.zip!vnm_admbnda_adm1_gov_20201027.shp'
      output: 'admin1'
    - source: 'vnm_adm_gov_20201027.zip!vnm_admbnda_adm2_gov_20201027.shp'
      output: 'admin2'
- country: Cambodia
  isocode: KH
  download:
    - dataset: 'cod-ab-khm'
      resource: 'khm_admbnda_adm0_gov_20181004.zip'
    - dataset: 'cod-ab-khm'
      resource: 'khm_admbnda_adm1_gov_20181004.zip'
    - dataset: 'cod-ab-khm'
      resource: 'khm_admbnda_adm2_gov_20181004.zip'
    - dataset: 'cod-ab-khm'
      resource: 'khm_admbnda_adm3_gov_20181004.zip'
  processing:
    - source: 'khm_admbnda_adm0_gov_20181004.zip'
      output: 'admin0'
    - source: 'khm_admbnda_adm1_gov_20181004.zip'
      output: 'admin1'
    - source: 'khm_admbnda_adm2_gov_20181004.zip'
      output: 'admin2'
    - source: 'khm_admbnda_adm3_gov_20181004.zip'
      output: 'admin3'

- country: Laos
  isocode: LA
  download:
    - dataset: 'cod-ab-lao'
      resource: 'lao_adm_ngd_20191112_SHP.zip'
  processing:
    - source: 'lao_adm_ngd_20191112_SHP.zip!lao_adm_ngd_20191112_SHP/lao_admbnda_adm0_ngd_20191112.shp'
      output: 'admin0'
    - source: 'lao_adm_ngd_20191112_SHP.zip!lao_adm_ngd_20191112_SHP/lao_admbnda_adm1_ngd_20191112.shp'
      output: 'admin1'
    - source: 'lao_adm_ngd_20191112_SHP.zip!lao_adm_ngd_20191112_SHP/lao_admbnda_adm2_ngd_20191112.shp'
      output: 'admin2'
